name: Release

on:
    release:
        types: [ published ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'liberica'
                    cache: 'gradle'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    gradle-version: 8.8

            -   name: Build artifacts
                run: gradle build

            -   name: Upload assets to GitHub, Modrinth and CurseForge
                uses: Kir-Antipov/mc-publish@v3.3
                with:
                    modrinth-id: QuPbmyCQ
                    modrinth-featured: false
                    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

                    curseforge-id: 945501
                    curseforge-token: ${{ secrets.CF_API_TOKEN }}

                    github-token: ${{ secrets.GITHUB_TOKEN }}

                    loaders: |
                        fabric

                    files: |
                        build/libs/!(*-@(dev-all|sources)).jar
                        build/libs/*-@(dev-all|sources).jar
